export const toolsInfo =[
    {
        id:1,
        name:'ABONO',
        key:'compost',
        cur:'url(assets/cursores/chakra_cursor.cur),pointer',
        position:{
            x:-45,
            y:-12
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'24px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:2,
        name:'AGUA',
        key:'water',
        cur:'url(assets/cursores/agua_cursor.cur),pointer',
        position:{
            x:-35,
            y:-12
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'24px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:3,
        name:'AZADÓN',
        key:'hoe',
        cur:'url(assets/cursores/azadon_cursor.cur),pointer',
        position:{
            x:-50,
            y:-12
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'24px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:4,
        name:'PALA',
        key:'shovel',
        cur:'url(assets/cursores/palaSeleccionada.cur),pointer',
        position:{
            x:-30,
            y:-12
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'24px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:5,
        name:'INSECTICIDA',
        key:'spray',
        cur:'url(assets/cursores/chisguete_cursor.cur),pointer',
        position:{
            x:-64,
            y:-10
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'20px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:6,
        name:'TIJERAS',
        key:'scissors',
        cur:'url(assets/cursores/tijeras_cursor.cur),pointer',
        position:{
            x:-45,
            y:-10
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'22px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
]

export const TOOLS_ATLAS = 'tools';