export const moduleOptionsInfo=[
    {
        id:1,
        title:'CALENDARIO\nAGROFESTIVO',
        icon:'carac',
        style:{
            fontFamily:'Helvetica',
            fontSize: '16px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        },
        scene:'CaracScene'
    },
    {
        id:2,
        title:'RELATOS\nVIVENCIALES',
        icon:'tales',
        style:{
            fontFamily:'Helvetica',
            fontSize: '16px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        },
        scene:'LibraryScene'
    },
    {
        id:3,
        title:'CHAKRA\nCOMUNITARIA',
        icon:'chakra',
        style:{
            fontFamily:'Helvetica',
            fontSize: '16px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        },
        scene:'ChakraScene'
    }
]

export const assistantButtonsInfo=[
    {
        id:1,
        title:'ATRAS',
        icon:'btn_arrow',
        position:{
            x:-22,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:2,
        title:'ADELANTE',
        icon:'btn_arrow',
        position:{
            x:-36,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'left'
        }
    },
    {
        id:3,
        title:'AYUDA',
        icon:'btn_hint',
        position:{
            x:-22,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:4,
        title:'GUIA',
        icon:'btn_guide',
        position:{
            x:-18,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:5,
        title:'SONIDO',
        icon:'btn_sound',
        position:{
            x:-26,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:6,
        title:'SILENCIO',
        icon:'btn_mute',
        position:{
            x:0,
            y:0
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'40px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:7,
        title:'SALTAR',
        icon:'btn_omit',
        position:{
            x:0,
            y:0
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'40px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    }
]

export const DEFAULT_WIDTH = 1900;
export const DEFAULT_HEIGHT = 1200;

export const MAIN_UI_ATLAS = 'main_ui';

export const AtlasInfo=[
    {
        key:'anden',
        path:'./assets/atlas/anden/',
        texture:'anden.png',
        atlas:'anden_atlas.json'
    },
    
    {
        key:'carac',
        path:'./assets/atlas/carac/',
        texture:'carac.png',
        atlas:'carac_atlas.json'
    },

    {
        key:'chakras',
        path:'./assets/atlas/chakras/',
        texture:'chakras.png',
        atlas:'chakras_atlas.json'
    },

    {
        key:'library',
        path:'./assets/atlas/library/',
        texture:'library.png',
        atlas:'library_atlas.json'
    },

    {
        key:'main_ui',
        path:'./assets/atlas/main_ui/',
        texture:'main_ui.png',
        atlas:'main_ui_atlas.json'
    },

    {
        key:'quiz',
        path:'./assets/atlas/quiz/',
        texture:'quiz.png',
        atlas:'quiz_atlas.json'
    },

    {
        key:'seeds',
        path:'./assets/atlas/seeds/',
        texture:'seeds.png',
        atlas:'seeds_atlas.json'
    },

    {
        key:'tools',
        path:'./assets/atlas/tools/',
        texture:'tools.png',
        atlas:'tools_atlas.json'
    },
]

export const separatorsInfo=[
    {
        id:1,
        name:'cuento',
        key:'separadorCuentos'
    },
    {
        id:2,
        name:'festivales',
        key:'separadorFestividades'
    },
    {
        id:3,
        name:'comidas',
        key:'separadorComidas'
    },
    {
        id:4,
        name:'señas',
        key:'separadorSeñas'
    }
];