export const moduleOptionsInfo=[
    {id:1,title:'CALENDARIO\nAGROFESTIVO',icon:'iconoCarac'},
    {id:2,title:'RELATOS\nVIVENCIALES',icon:'iconoRelatos'},
    {id:3,title:'CHAKRA\nCOMUNITARIA',icon:'iconoChakra'}
]

export const assistantButtonsInfo=[
    {
        id:1,
        title:'ATRAS',
        icon:'flecha',
        position:{
            x:-22,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:2,
        title:'ADELANTE',
        icon:'flecha',
        position:{
            x:-36,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'left'
        }
    },
    {
        id:3,
        title:'AYUDA',
        icon:'ayuda',
        position:{
            x:-22,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:4,
        title:'GUIA',
        icon:'guia',
        position:{
            x:-18,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:5,
        title:'SONIDO',
        icon:'sonido',
        position:{
            x:-26,
            y:-8
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'14px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:6,
        title:'SILENCIO',
        icon:'silencio',
        position:{
            x:0,
            y:0
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'40px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    },
    {
        id:7,
        title:'SALTAR',
        icon:'saltar',
        position:{
            x:0,
            y:0
        },
        style:{
            fontFamily:'Helvetica',
            fontSize:'40px',
            color:'#000',
            stroke:'#000',
            strokeThickness:1,
            align:'center'
        }
    }
]

export const DEFAULT_WIDTH = 1900;
export const DEFAULT_HEIGHT = 1200;