export const talesStates= [
    {
        id:1,
        key:'new',
        value:'nuevo',
        props:{
            x:50,
            y:-70,
            scale:1
        }
    },
    {
        id:2,
        key:'complete',
        value:'liston',
        props:{
            x:45,
            y:-45,
            scale:0.9
        }
    },
    {
        id:3,
        key:'blocked',
        value:'candado',
        props:{
            x:40,
            y:-50,
            scale:0.8
        }
    }
]